/* ORBITAL — component library bundle (behaviors · ui · overlays · motion).
   Generated by concatenation; edit the sources or regenerate. Load orbital-theme.js separately, after the page builds its nav. */

/* ===== orbital-behaviors.js ===== */
/* ============================================================
   HM BEHAVIORS — the effectful substrate
   "Swiss Bank in Orbital Cyberspace"

   UI components are products of behaviors (per purescript-radix):

     Dialog        = Disclosure × FocusTrap × ScrollLock × AriaHider × Dismissable
     DropdownMenu  = Disclosure × Positioning × RovingFocus × Dismissable
     Popover       = Disclosure × Positioning × Dismissable
     Tooltip       = Disclosure × Positioning
     CommandPalette= Dialog × Selection × Filtering

   Each behavior here is the small, DOM-effectful piece — the part that
   would be FFI in Hydrogen (cf. FocusTrap.js / AriaHider.js / ScrollLock.js).
   Pure state machines (Disclosure, Selection, Navigation) live in orbital-ui.js.

   Convention: every behavior is a factory returning a uniform handle
       { activate(): void, deactivate(): void, update?(): void }
   so an overlay just composes a list of handles and flips them together.

   Halogen mapping: each maps to a Hydrogen behavior whose `activate`
   is an Effect run in handleAction (or a subscription), `deactivate`
   the matching cleanup.
   ============================================================ */
(function (root) {
  'use strict';

  const FOCUSABLE = [
    'a[href]', 'button:not([disabled])', 'input:not([disabled])',
    'select:not([disabled])', 'textarea:not([disabled])',
    '[tabindex]:not([tabindex="-1"])', '[contenteditable="true"]',
  ].join(',');
  function focusables(container) {
    return Array.prototype.filter.call(container.querySelectorAll(FOCUSABLE),
      (el) => el.offsetWidth > 0 || el.offsetHeight > 0 || el === document.activeElement);
  }

  /* ---- FocusTrap : keep Tab focus inside `container` ---- */
  function FocusTrap(container, opts) {
    const o = opts || {};
    let prev = null;
    function onKey(e) {
      if (e.key !== 'Tab') return;
      const f = focusables(container);
      if (!f.length) { e.preventDefault(); return; }
      const first = f[0], last = f[f.length - 1];
      if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
      else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
    }
    return {
      activate() {
        prev = document.activeElement;
        container.addEventListener('keydown', onKey);
        const f = focusables(container);
        const target = o.initialFocus || f[0] || container;
        requestAnimationFrame(() => { try { target.focus({ preventScroll: true }); } catch (e) {} });
      },
      deactivate() {
        container.removeEventListener('keydown', onKey);
        if (o.returnFocus !== false && prev && prev.focus) { try { prev.focus({ preventScroll: true }); } catch (e) {} }
      },
    };
  }

  /* ---- Dismissable : Esc + outside-pointer closes ---- */
  function Dismissable(el, opts) {
    const o = opts || {};
    function onKey(e) { if (e.key === 'Escape' && o.escape !== false) { e.stopPropagation(); o.onDismiss && o.onDismiss('escape'); } }
    function onDown(e) {
      if (o.outside === false) return;
      if (el.contains(e.target)) return;
      if (o.ignore && o.ignore(e.target)) return;
      o.onDismiss && o.onDismiss('outside');
    }
    return {
      activate() { document.addEventListener('keydown', onKey, true); setTimeout(() => document.addEventListener('pointerdown', onDown, true), 0); },
      deactivate() { document.removeEventListener('keydown', onKey, true); document.removeEventListener('pointerdown', onDown, true); },
    };
  }

  /* ---- ScrollLock : freeze body scroll, compensate the scrollbar ---- */
  let lockCount = 0, savedPad = '', savedOv = '';
  function ScrollLock() {
    return {
      activate() {
        if (lockCount++ === 0) {
          const sw = window.innerWidth - document.documentElement.clientWidth;
          savedOv = document.body.style.overflow; savedPad = document.body.style.paddingRight;
          document.body.style.overflow = 'hidden';
          if (sw > 0) document.body.style.paddingRight = sw + 'px';
        }
      },
      deactivate() {
        if (--lockCount <= 0) { lockCount = 0; document.body.style.overflow = savedOv; document.body.style.paddingRight = savedPad; }
      },
    };
  }

  /* ---- AriaHider : aria-hidden the rest of the page from AT ---- */
  function AriaHider(keep) {
    let touched = [];
    return {
      activate() {
        touched = [];
        Array.prototype.forEach.call(document.body.children, (c) => {
          if (c === keep || c.contains(keep)) return;
          if (c.getAttribute('aria-hidden') === 'true') return;
          c.setAttribute('aria-hidden', 'true'); touched.push(c);
        });
      },
      deactivate() { touched.forEach((c) => c.removeAttribute('aria-hidden')); touched = []; },
    };
  }

  /* ---- Positioning : place `floating` next to `anchor` ---- */
  function Positioning(anchor, floating, opts) {
    const o = opts || {};
    const side = o.side || 'bottom';     // top | bottom | left | right
    const align = o.align || 'start';    // start | center | end
    const gap = o.gap == null ? 6 : o.gap;
    function place() {
      const a = anchor.getBoundingClientRect();
      const f = floating.getBoundingClientRect();
      let top, left;
      if (side === 'bottom') top = a.bottom + gap;
      else if (side === 'top') top = a.top - f.height - gap;
      else top = a.top;
      if (side === 'left') left = a.left - f.width - gap;
      else if (side === 'right') left = a.right + gap;
      else { // top/bottom -> horizontal align
        left = align === 'center' ? a.left + a.width / 2 - f.width / 2 : align === 'end' ? a.right - f.width : a.left;
      }
      if (side === 'left' || side === 'right') {
        top = align === 'center' ? a.top + a.height / 2 - f.height / 2 : align === 'end' ? a.bottom - f.height : a.top;
      }
      const vw = document.documentElement.clientWidth, vh = document.documentElement.clientHeight;
      left = Math.max(8, Math.min(left, vw - f.width - 8));
      top = Math.max(8, Math.min(top, vh - f.height - 8));
      floating.style.position = 'fixed';
      floating.style.top = Math.round(top) + 'px';
      floating.style.left = Math.round(left) + 'px';
    }
    return {
      activate() { place(); window.addEventListener('scroll', place, true); window.addEventListener('resize', place); },
      deactivate() { window.removeEventListener('scroll', place, true); window.removeEventListener('resize', place); },
      update: place,
    };
  }

  /* ---- compose() : run a list of behavior handles as one ---- */
  function compose(list) {
    const hs = list.filter(Boolean);
    return {
      activate() { hs.forEach((h) => h.activate && h.activate()); },
      deactivate() { for (let i = hs.length - 1; i >= 0; i--) hs[i].deactivate && hs[i].deactivate(); },
      update() { hs.forEach((h) => h.update && h.update()); },
    };
  }

  root.ORBITALBehaviors = { FocusTrap, Dismissable, ScrollLock, AriaHider, Positioning, compose, focusables };
})(window);


/* ===== orbital-ui.js ===== */
/* ============================================================
   ORBITAL UI — Hypermodern primitive component library
   "Swiss Bank in Orbital Cyberspace"

   Authored in a Radix-shaped idiom so the port to Halogen/PureScript
   is mechanical:

     • Each primitive is a factory  ORBITAL.Thing(props) -> { el, ...api }
     • Props follow Radix's controlled/uncontrolled contract:
         value / defaultValue / onValueChange   (or pressed/open/…)
     • Structure is part-based:   [data-part="item|trigger|content|…"]
     • State is expressed as data-attributes, never ad-hoc classes:
         data-state="on|off|open|closed|copied", data-disabled, aria-*
     • Behavior is headless; all styling lives in orbital.css keyed on the
       data-attributes above.

   Halogen mapping (for the compiler):
     props            -> component Input
     internal current -> component State
     onValueChange    -> component Output (raised message)
     setValue/api     -> component Query
     render below     -> Halogen.HTML keyed on State -> data-state
   ============================================================ */
(function (root) {
  'use strict';

  /* ---- tiny hyperscript: h(tag, props?, ...children) ---- */
  function h(tag, props, ...kids) {
    const el = document.createElement(tag);
    if (props) for (const k in props) {
      const v = props[k];
      if (v == null || v === false) continue;
      if (k === 'class') el.className = v;
      else if (k === 'html') el.innerHTML = v;
      else if (k === 'dataset') for (const d in v) el.dataset[d] = v[d];
      else if (k.slice(0, 2) === 'on' && typeof v === 'function') el.addEventListener(k.slice(2).toLowerCase(), v);
      else if (v === true) el.setAttribute(k, '');
      else el.setAttribute(k, v);
    }
    for (const kid of kids.flat()) {
      if (kid == null || kid === false) continue;
      el.append(kid.nodeType ? kid : document.createTextNode(kid));
    }
    return el;
  }

  /* controlled/uncontrolled helper: resolves the active value source */
  function controllable(props, key, def) {
    const cap = key[0].toUpperCase() + key.slice(1);
    const controlled = props[key] !== undefined;
    let current = controlled ? props[key] : (props['default' + cap] !== undefined ? props['default' + cap] : def);
    return {
      get: () => current,
      set: (v) => { current = v; },
      controlled,
    };
  }

  /* =========================================================
     SegmentedControl  (Radix ToggleGroup, type="single")
     props: { options:[{value,label,disabled?}], value?, defaultValue?,
              onValueChange?, ariaLabel? }
     ========================================================= */
  function SegmentedControl(props) {
    const p = props || {};
    const opts = p.options || [];
    const st = controllable(p, 'value', opts[0] && opts[0].value);

    const items = opts.map((o) =>
      h('button', {
        type: 'button', class: 'seg-item', 'data-part': 'item', role: 'radio',
        value: o.value, 'aria-checked': 'false',
        disabled: o.disabled ? '' : null,
        tabindex: '-1',
      }, o.label)
    );
    const el = h('div', { class: p.class || 'seg', 'data-orbital': 'segmented', role: 'radiogroup', 'aria-label': p.ariaLabel || 'Select' }, items);

    function paint() {
      items.forEach((b) => {
        const on = b.getAttribute('value') === String(st.get());
        b.dataset.state = on ? 'on' : 'off';
        b.setAttribute('aria-checked', on ? 'true' : 'false');
        b.tabIndex = on ? 0 : -1;
      });
    }
    function choose(v, focus) {
      if (v == null) return;
      const o = opts.find((x) => String(x.value) === String(v));
      if (!o || o.disabled) return;
      st.set(v); paint();
      if (focus) { const b = items.find((x) => x.getAttribute('value') === String(v)); b && b.focus(); }
      if (p.onValueChange) p.onValueChange(v);
    }
    items.forEach((b, i) => {
      b.addEventListener('click', () => choose(b.getAttribute('value')));
      b.addEventListener('keydown', (e) => {
        const dir = e.key === 'ArrowRight' || e.key === 'ArrowDown' ? 1 : e.key === 'ArrowLeft' || e.key === 'ArrowUp' ? -1 : 0;
        if (!dir) return;
        e.preventDefault();
        let j = i;
        do { j = (j + dir + opts.length) % opts.length; } while (opts[j].disabled && j !== i);
        choose(opts[j].value, true);
      });
    });
    paint();
    return { el, get value() { return st.get(); }, setValue: (v) => choose(v) };
  }

  /* =========================================================
     Tabs  (Radix Tabs)
     props: { tabs:[{value,label,panel?,disabled?}], value?, defaultValue?,
              onValueChange?, ariaLabel? }
     If a tab supplies `panel` (node|string) a tabpanel is rendered and
     toggled; otherwise only onValueChange fires (panels managed outside).
     ========================================================= */
  function Tabs(props) {
    const p = props || {};
    const tabs = p.tabs || [];
    const st = controllable(p, 'value', tabs[0] && tabs[0].value);
    const hasPanels = tabs.some((t) => t.panel != null);

    const triggers = tabs.map((t) =>
      h('button', {
        type: 'button', class: 'tabs-trigger', 'data-part': 'tab', role: 'tab',
        value: t.value, disabled: t.disabled ? '' : null, tabindex: '-1',
      }, t.label)
    );
    const list = h('div', { class: 'tabs-list', 'data-part': 'list', role: 'tablist', 'aria-label': p.ariaLabel || 'Tabs' }, triggers);
    const panels = hasPanels ? tabs.map((t) =>
      h('div', { class: 'tabs-content', 'data-part': 'panel', role: 'tabpanel' }, t.panel && t.panel.nodeType ? t.panel : (t.panel ? h('div', { html: String(t.panel) }) : null))
    ) : [];
    const el = h('div', { class: 'tabset', 'data-orbital': 'tabs' }, list, ...panels);

    function paint() {
      triggers.forEach((b) => {
        const on = b.getAttribute('value') === String(st.get());
        b.dataset.state = on ? 'active' : 'inactive';
        b.setAttribute('aria-selected', on ? 'true' : 'false');
        b.tabIndex = on ? 0 : -1;
      });
      if (hasPanels) panels.forEach((pn, i) => { pn.dataset.state = tabs[i].value === st.get() ? 'active' : 'inactive'; pn.hidden = tabs[i].value !== st.get(); });
    }
    function choose(v, focus) {
      const t = tabs.find((x) => String(x.value) === String(v));
      if (!t || t.disabled) return;
      st.set(v); paint();
      if (focus) { const b = triggers.find((x) => x.getAttribute('value') === String(v)); b && b.focus(); }
      if (p.onValueChange) p.onValueChange(v);
    }
    triggers.forEach((b, i) => {
      b.addEventListener('click', () => choose(b.getAttribute('value')));
      b.addEventListener('keydown', (e) => {
        const dir = e.key === 'ArrowRight' ? 1 : e.key === 'ArrowLeft' ? -1 : 0;
        if (!dir) return; e.preventDefault();
        let j = i; do { j = (j + dir + tabs.length) % tabs.length; } while (tabs[j].disabled && j !== i);
        choose(tabs[j].value, true);
      });
    });
    paint();
    return { el, get value() { return st.get(); }, setValue: (v) => choose(v) };
  }

  /* =========================================================
     Toggle  (Radix Toggle — a single two-state button)
     props: { label, pressed?, defaultPressed?, onPressedChange?, disabled? }
     ========================================================= */
  function Toggle(props) {
    const p = props || {};
    const st = controllable(p, 'pressed', false);
    const el = h('button', {
      type: 'button', class: 'toggle', 'data-orbital': 'toggle',
      'aria-pressed': 'false', disabled: p.disabled ? '' : null,
    }, p.label || '');
    function paint() { el.dataset.state = st.get() ? 'on' : 'off'; el.setAttribute('aria-pressed', st.get() ? 'true' : 'false'); }
    el.addEventListener('click', () => { if (p.disabled) return; st.set(!st.get()); paint(); if (p.onPressedChange) p.onPressedChange(st.get()); });
    paint();
    return { el, get pressed() { return st.get(); }, setPressed: (v) => { st.set(!!v); paint(); } };
  }

  /* =========================================================
     Switch  (Radix Switch — track + thumb)
     props: { pressed?, defaultPressed?, onCheckedChange?, label?, disabled? }
     ========================================================= */
  function Switch(props) {
    const p = props || {};
    const st = controllable(p, 'pressed', false);
    const thumb = h('span', { class: 'switch-thumb', 'data-part': 'thumb' });
    const ctl = h('button', {
      type: 'button', class: 'switch', 'data-orbital': 'switch', role: 'switch',
      'aria-checked': 'false', disabled: p.disabled ? '' : null,
    }, thumb);
    function paint() { ctl.dataset.state = st.get() ? 'checked' : 'unchecked'; ctl.setAttribute('aria-checked', st.get() ? 'true' : 'false'); }
    ctl.addEventListener('click', () => { if (p.disabled) return; st.set(!st.get()); paint(); if (p.onCheckedChange) p.onCheckedChange(st.get()); });
    paint();
    const el = p.label
      ? h('label', { class: 'switch-row', 'data-part': 'root' }, ctl, h('span', { class: 'switch-label', 'data-part': 'label' }, p.label))
      : ctl;
    if (p.label) el.addEventListener('click', (e) => { if (e.target !== ctl && !ctl.contains(e.target)) ctl.click(); });
    return { el, control: ctl, get checked() { return st.get(); }, setChecked: (v) => { st.set(!!v); paint(); } };
  }

  /* =========================================================
     CopyButton  (best-in-role: Forge clone-panel logic)
     props: { value, label?, copiedLabel?, onCopy? }
     ========================================================= */
  function CopyButton(props) {
    const p = props || {};
    const el = h('button', { type: 'button', class: 'copybtn', 'data-orbital': 'copy', 'data-state': 'idle' }, p.label || 'Copy');
    let t;
    function done(ok) {
      el.dataset.state = ok ? 'copied' : 'error';
      el.textContent = ok ? (p.copiedLabel || 'Copied') : 'Press ⌘C';
      clearTimeout(t); t = setTimeout(() => { el.dataset.state = 'idle'; el.textContent = p.label || 'Copy'; }, 1400);
      if (ok && p.onCopy) p.onCopy(p.value);
    }
    el.addEventListener('click', () => {
      const text = typeof p.value === 'function' ? p.value() : p.value;
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(() => done(true)).catch(() => fallback(text));
      } else fallback(text);
    });
    function fallback(text) {
      const ta = h('textarea', { style: 'position:fixed;opacity:0;pointer-events:none' }); ta.value = text;
      document.body.append(ta); ta.select();
      let ok = false; try { ok = document.execCommand('copy'); } catch (e) {}
      ta.remove(); done(ok);
    }
    return { el, setValue: (v) => { p.value = v; } };
  }

  /* =========================================================
     Disclosure  (Radix Collapsible)
     props: { label, content:(node|string|()=>node), open?, defaultOpen?, onOpenChange? }
     ========================================================= */
  function Disclosure(props) {
    const p = props || {};
    const st = controllable(p, 'open', false);
    const body = p.content && p.content.nodeType ? p.content
      : typeof p.content === 'function' ? p.content()
      : h('div', { html: String(p.content || '') });
    const content = h('div', { class: 'disclosure-content', 'data-part': 'content', role: 'region' }, body);
    const caret = h('span', { class: 'disclosure-caret', 'data-part': 'caret', 'aria-hidden': 'true' });
    const trigger = h('button', { type: 'button', class: 'disclosure-trigger', 'data-part': 'trigger', 'aria-expanded': 'false' }, h('span', null, p.label || 'Details'), caret);
    const el = h('div', { class: 'disclosure', 'data-orbital': 'disclosure' }, trigger, content);
    function paint() {
      const o = st.get();
      el.dataset.state = o ? 'open' : 'closed';
      content.dataset.state = o ? 'open' : 'closed';
      content.hidden = !o;
      trigger.setAttribute('aria-expanded', o ? 'true' : 'false');
    }
    trigger.addEventListener('click', () => { st.set(!st.get()); paint(); if (p.onOpenChange) p.onOpenChange(st.get()); });
    paint();
    return { el, get open() { return st.get(); }, setOpen: (v) => { st.set(!!v); paint(); } };
  }

  /* =========================================================
     PageIndicator  (the site's footer section scrubber)
     props: { count, value?, defaultValue?, onValueChange?, labels? }
     A slim track with a glowing thumb; click or ←/→ to scrub.
     ========================================================= */
  function PageIndicator(props) {
    const p = props || {};
    const count = Math.max(1, p.count || 1);
    const st = controllable(p, 'value', 0);
    const thumb = h('div', { class: 'pageind-thumb', 'data-part': 'thumb' });
    const track = h('div', {
      class: 'pageind', 'data-orbital': 'page-indicator', role: 'slider', tabindex: '0',
      'aria-valuemin': '0', 'aria-valuemax': String(count - 1), 'aria-label': p.ariaLabel || 'Section',
    }, thumb);
    const labelEl = p.labels ? h('span', { class: 'pageind-label' }) : null;
    function paint() {
      const tw = 100 / count, travel = 100 - tw;
      thumb.style.width = tw + '%';
      thumb.style.left = (count > 1 ? (st.get() / (count - 1)) * travel : 0) + '%';
      track.setAttribute('aria-valuenow', String(st.get()));
      if (labelEl && p.labels) labelEl.textContent = p.labels[st.get()] || '';
    }
    function go(i) {
      i = Math.max(0, Math.min(count - 1, i));
      if (i === st.get()) return;
      st.set(i); paint();
      if (p.onValueChange) p.onValueChange(i);
    }
    track.addEventListener('click', (e) => { const r = track.getBoundingClientRect(); go(Math.round(((e.clientX - r.left) / r.width) * (count - 1))); });
    track.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowRight' || e.key === 'ArrowUp') { e.preventDefault(); go(st.get() + 1); }
      else if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') { e.preventDefault(); go(st.get() - 1); }
      else if (e.key === 'Home') { e.preventDefault(); go(0); }
      else if (e.key === 'End') { e.preventDefault(); go(count - 1); }
    });
    paint();
    const el = labelEl ? h('div', { class: 'pageind-row' }, labelEl, track) : track;
    return { el, track, get value() { return st.get(); }, setValue: (i) => go(i) };
  }

  /* =========================================================
     ScrollProgress  (the Archive reading-progress bar)
     props: { source?, ariaLabel? }
       source: window (default) | a scrollable element
     A thin fill that tracks scroll position 0→100%. Positioning
     (fixed under the header, or sticky atop a container) is CSS;
     the primitive just owns the fill + scroll wiring.
     ========================================================= */
  function ScrollProgress(props) {
    const p = props || {};
    const src = p.source || window;
    const fill = h('div', { class: 'scrollprog-fill', 'data-part': 'fill' });
    const el = h('div', { class: 'scrollprog', 'data-orbital': 'scroll-progress', role: 'progressbar', 'aria-label': p.ariaLabel || 'Reading progress', 'aria-valuemin': '0', 'aria-valuemax': '100' }, fill);
    function ratio() {
      const d = (src === window) ? (document.scrollingElement || document.documentElement) : src;
      const max = d.scrollHeight - d.clientHeight;
      return max > 0 ? d.scrollTop / max : 0;
    }
    function update() {
      const v = Math.max(0, Math.min(1, ratio()));
      fill.style.width = (v * 100) + '%';
      el.setAttribute('aria-valuenow', String(Math.round(v * 100)));
    }
    (src === window ? window : src).addEventListener('scroll', update, { passive: true });
    window.addEventListener('resize', update);
    requestAnimationFrame(update);
    return { el, fill, update };
  }

  /* ---- syntax highlighting (optional; falls back to escaped text) ---- */
  function esc(s) { return String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c])); }
  const HL = { cpp: 'cpp', 'c++': 'cpp', c: 'cpp', cuda: 'cpp', rust: 'rust', nix: 'nix', lean: 'lean', shell: 'bash', bash: 'bash', sh: 'bash', python: 'python', py: 'python', markdown: 'markdown', md: 'markdown', cmake: 'cmake', js: 'javascript', javascript: 'javascript', ts: 'typescript', json: 'json', html: 'xml', xml: 'xml', css: 'css' };
  function hl(code, lang) {
    const id = HL[(lang || '').toLowerCase()];
    if (window.hljs && id && hljs.getLanguage && hljs.getLanguage(id)) {
      try { return hljs.highlight(code, { language: id, ignoreIllegals: true }).value; } catch (e) {}
    }
    return esc(code);
  }

  /* =========================================================
     CodeSnippet  (lightweight soft code box)
     props: { code, lang?, copy? }
     ========================================================= */
  function CodeSnippet(props) {
    const p = props || {};
    const code = h('code', { class: 'hljs' }); code.innerHTML = hl(p.code || '', p.lang);
    const pre = h('pre', { class: 'codeblk', 'data-orbital': 'code-snippet' }, code);
    if (p.lang && !p.copy) pre.dataset.lang = p.lang;
    if (!p.copy) return { el: pre, pre };
    const cp = CopyButton({ value: () => p.code, label: 'Copy' });
    cp.el.classList.add('codeblk-copy');
    return { el: h('div', { class: 'codeblk-wrap' }, pre, cp.el), pre };
  }

  /* =========================================================
     CodeViewer  (serious, GitHub-style — the forge interface)
     props: { code, lang?, path?, startLine?, highlightLines?[], maxHeight? }
       sticky line-number gutter · vertical + horizontal scroll ·
       header (path · lang · lines · copy) · click a line # to band it
     ========================================================= */
  function CodeViewer(props) {
    const p = props || {};
    const lines = String(p.code || '').replace(/\n$/, '').split('\n');
    const start = p.startLine || 1;
    const initial = new Set(p.highlightLines || []);

    const gutter = h('div', { class: 'cv-gutter', 'aria-hidden': 'true' });
    lines.forEach((_, i) => {
      const n = start + i;
      const s = h('span', { class: 'cv-ln', 'data-ln': String(n) }, String(n));
      if (initial.has(n)) s.classList.add('on');
      gutter.append(s);
    });
    const codeEl = h('code', { class: 'hljs' }); codeEl.innerHTML = hl(lines.join('\n'), p.lang);
    const pre = h('pre', { class: 'cv-pre' }, codeEl);
    const bands = h('div', { class: 'cv-bands', 'aria-hidden': 'true' });
    const grid = h('div', { class: 'cv-grid' }, bands, gutter, pre);
    const scroll = h('div', { class: 'cv-scroll' }, grid);
    if (p.maxHeight) scroll.style.maxHeight = typeof p.maxHeight === 'number' ? p.maxHeight + 'px' : p.maxHeight;

    function band(lo, hi) {
      const d = h('div', { class: 'cv-band' });
      d.style.top = 'calc(var(--cv-pad) + ' + (lo - start) + ' * 1lh)';
      d.style.height = 'calc(' + (hi - lo + 1) + ' * 1lh)';
      return d;
    }
    let anchor = null, focusLn = null, dragging = false;
    if (initial.size) { const a = [...initial]; anchor = Math.min(...a); focusLn = Math.max(...a); }
    function render() {
      const lo = anchor == null ? null : Math.min(anchor, focusLn);
      const hi = anchor == null ? null : Math.max(anchor, focusLn);
      gutter.querySelectorAll('.cv-ln').forEach((s) => { const n = +s.dataset.ln; s.classList.toggle('on', lo != null && n >= lo && n <= hi); });
      bands.innerHTML = '';
      if (lo != null) bands.append(band(lo, hi));
    }
    function selectAt(n, extend) { if (extend && anchor != null) focusLn = n; else { anchor = n; focusLn = n; } render(); }
    gutter.querySelectorAll('.cv-ln').forEach((s) => {
      const n = +s.dataset.ln;
      s.addEventListener('mousedown', (e) => { e.preventDefault(); dragging = true; grid.classList.add('selecting'); selectAt(n, e.shiftKey); });
      s.addEventListener('mouseenter', () => { if (dragging) { focusLn = n; render(); } });
    });
    document.addEventListener('mouseup', () => { if (dragging) { dragging = false; grid.classList.remove('selecting'); } });
    render();

    let head = null;
    if (p.path || p.lang) {
      const copy = CopyButton({ value: () => lines.join('\n'), label: 'Copy' }); copy.el.classList.add('cv-btn');
      head = h('div', { class: 'cv-head' },
        h('span', { class: 'cv-path' }, p.path || 'untitled'),
        h('span', { class: 'cv-meta' }, (p.lang ? p.lang + ' · ' : '') + lines.length + ' lines'),
        h('div', { class: 'cv-actions' }, copy.el));
    }
    const el = h('div', { class: 'codeview', 'data-orbital': 'code-viewer' }, head, scroll);
    return {
      el, scroll,
      select: (lo, hi) => { anchor = lo; focusLn = hi == null ? lo : hi; render(); },
      clear: () => { anchor = focusLn = null; render(); },
    };
  }

  /* =========================================================
     FORM CONTROLS
     ========================================================= */

  /* TextField — label + input/textarea, optional hint/error */
  function TextField(props) {
    const p = props || {};
    const id = 'tf-' + Math.random().toString(36).slice(2, 7);
    const input = h(p.multiline ? 'textarea' : 'input', {
      class: 'field-input', id, type: p.type || 'text', placeholder: p.placeholder || null,
      value: p.value != null ? p.value : null, rows: p.multiline ? (p.rows || 3) : null,
      disabled: p.disabled ? '' : null, spellcheck: 'false',
    });
    if (p.value != null) input.value = p.value;
    const hint = p.hint ? h('span', { class: 'field-hint' }, p.hint) : null;
    const err = h('span', { class: 'field-error' });
    const el = h('div', { class: 'field-root', 'data-orbital': 'text-field' },
      p.label ? h('label', { class: 'field-label', for: id }, p.label) : null,
      h('div', { class: 'field-box' }, p.prefix || null, input), hint, err);
    input.addEventListener('input', () => { el.dataset.state = ''; err.textContent = ''; if (p.onInput) p.onInput(input.value); });
    return {
      el, input,
      get value() { return input.value; }, setValue: (v) => { input.value = v; },
      setError: (m) => { el.dataset.state = m ? 'error' : ''; err.textContent = m || ''; },
    };
  }

  /* Select — native-backed, styled trigger */
  function Select(props) {
    const p = props || {};
    const st = controllable(p, 'value', p.options && p.options[0] && p.options[0].value);
    const sel = h('select', { class: 'select-native', disabled: p.disabled ? '' : null, 'aria-label': p.ariaLabel || 'Select' },
      ...(p.options || []).map((o) => h('option', { value: o.value }, o.label)));
    sel.value = st.get();
    const el = h('div', { class: 'select-root', 'data-orbital': 'select' }, sel, h('span', { class: 'select-caret', 'aria-hidden': 'true' }));
    sel.addEventListener('change', () => { st.set(sel.value); if (p.onValueChange) p.onValueChange(sel.value); });
    return { el, get value() { return st.get(); }, setValue: (v) => { st.set(v); sel.value = v; } };
  }

  /* Checkbox */
  function Checkbox(props) {
    const p = props || {};
    const st = controllable(p, 'checked', false);
    const box = h('span', { class: 'checkbox-box', 'data-part': 'box' }, h('span', { class: 'checkbox-check' }));
    const ctl = h('button', { type: 'button', class: 'checkbox', role: 'checkbox', 'aria-checked': 'false', disabled: p.disabled ? '' : null }, box);
    function paint() { ctl.dataset.state = st.get() ? 'checked' : 'unchecked'; ctl.setAttribute('aria-checked', st.get() ? 'true' : 'false'); }
    ctl.addEventListener('click', () => { if (p.disabled) return; st.set(!st.get()); paint(); if (p.onCheckedChange) p.onCheckedChange(st.get()); });
    paint();
    const el = p.label ? h('label', { class: 'checkbox-row' }, ctl, h('span', { class: 'checkbox-label' }, p.label)) : ctl;
    if (p.label) el.addEventListener('click', (e) => { if (e.target !== ctl && !ctl.contains(e.target)) ctl.click(); });
    return { el, control: ctl, get checked() { return st.get(); }, setChecked: (v) => { st.set(!!v); paint(); } };
  }

  /* RadioGroup */
  function RadioGroup(props) {
    const p = props || {};
    const opts = p.options || [];
    const st = controllable(p, 'value', opts[0] && opts[0].value);
    const items = opts.map((o) => {
      const dot = h('span', { class: 'radio-dot' });
      const btn = h('button', { type: 'button', class: 'radio', role: 'radio', value: o.value, 'aria-checked': 'false', disabled: o.disabled ? '' : null, tabindex: '-1' }, dot);
      return h('label', { class: 'radio-row' }, btn, h('span', { class: 'radio-label' }, o.label));
    });
    const el = h('div', { class: 'radio-group', 'data-orbital': 'radio-group', role: 'radiogroup', 'aria-label': p.ariaLabel || 'Choose' }, ...items);
    const btns = items.map((r) => r.querySelector('.radio'));
    function paint() { btns.forEach((b) => { const on = b.getAttribute('value') === String(st.get()); b.dataset.state = on ? 'checked' : 'unchecked'; b.setAttribute('aria-checked', on ? 'true' : 'false'); b.tabIndex = on ? 0 : -1; }); }
    function choose(v, focus) { const o = opts.find((x) => String(x.value) === String(v)); if (!o || o.disabled) return; st.set(v); paint(); if (focus) { const b = btns.find((x) => x.getAttribute('value') === String(v)); b && b.focus(); } if (p.onValueChange) p.onValueChange(v); }
    btns.forEach((b, i) => {
      b.addEventListener('click', () => choose(b.getAttribute('value')));
      b.addEventListener('keydown', (e) => { const dir = e.key === 'ArrowDown' || e.key === 'ArrowRight' ? 1 : e.key === 'ArrowUp' || e.key === 'ArrowLeft' ? -1 : 0; if (!dir) return; e.preventDefault(); let j = i; do { j = (j + dir + opts.length) % opts.length; } while (opts[j].disabled && j !== i); choose(opts[j].value, true); });
    });
    paint();
    return { el, get value() { return st.get(); }, setValue: (v) => choose(v) };
  }

  /* Slider — single-thumb range */
  function Slider(props) {
    const p = props || {};
    const min = p.min == null ? 0 : p.min, max = p.max == null ? 100 : p.max, step = p.step || 1;
    const st = controllable(p, 'value', p.defaultValue != null ? p.defaultValue : min);
    const range = h('div', { class: 'slider-range' });
    const thumb = h('div', { class: 'slider-thumb', tabindex: p.disabled ? '-1' : '0', role: 'slider', 'aria-valuemin': String(min), 'aria-valuemax': String(max) });
    const track = h('div', { class: 'slider-track' }, range, thumb);
    const el = h('div', { class: 'slider', 'data-orbital': 'slider', 'data-disabled': p.disabled ? '' : null }, track);
    function pct() { return (st.get() - min) / (max - min); }
    function paint() { const x = pct() * 100; range.style.width = x + '%'; thumb.style.left = x + '%'; thumb.setAttribute('aria-valuenow', String(st.get())); }
    function set(v) { v = Math.max(min, Math.min(max, Math.round((v - min) / step) * step + min)); if (v === st.get()) return; st.set(v); paint(); if (p.onValueChange) p.onValueChange(v); }
    function fromX(clientX) { const r = track.getBoundingClientRect(); set(min + ((clientX - r.left) / r.width) * (max - min)); }
    let drag = false;
    track.addEventListener('pointerdown', (e) => { if (p.disabled) return; drag = true; thumb.setPointerCapture && thumb.setPointerCapture(e.pointerId); fromX(e.clientX); thumb.focus(); });
    track.addEventListener('pointermove', (e) => { if (drag) fromX(e.clientX); });
    document.addEventListener('pointerup', () => { drag = false; });
    thumb.addEventListener('keydown', (e) => { const d = e.key === 'ArrowRight' || e.key === 'ArrowUp' ? step : e.key === 'ArrowLeft' || e.key === 'ArrowDown' ? -step : 0; if (!d) return; e.preventDefault(); set(st.get() + d); });
    paint();
    return { el, get value() { return st.get(); }, setValue: set };
  }

  /* =========================================================
     DataTable — sortable, selectable rows
     props: { columns:[{key,label,align?,sortable?,render?(row)}],
              rows:[obj], selectable?, rowKey?(row), onSelectionChange?,
              onRowClick?, sort?{key,dir} }
     ========================================================= */
  function DataTable(props) {
    const p = props || {};
    const cols = p.columns || [];
    let rows = (p.rows || []).slice();
    let sort = p.sort || null;
    const keyOf = p.rowKey || ((r, i) => i);
    const selected = new Set();

    const headCells = cols.map((c) => {
      const th = h('th', { class: 'dt-th' + (c.sortable ? ' is-sortable' : '') + (c.align === 'right' ? ' is-right' : ''), 'data-key': c.key },
        h('span', null, c.label), c.sortable ? h('span', { class: 'dt-sort', 'aria-hidden': 'true' }) : null);
      if (c.sortable) th.addEventListener('click', () => toggleSort(c.key));
      return th;
    });
    const selectAll = p.selectable ? h('th', { class: 'dt-th dt-check' }) : null;
    const theadRow = h('tr', null, selectAll, ...headCells);
    const tbody = h('tbody', { class: 'dt-body' });
    const table = h('table', { class: 'dt' }, h('thead', { class: 'dt-head' }, theadRow), tbody);
    const el = h('div', { class: 'tablewrap', 'data-orbital': 'data-table' }, table);

    function toggleSort(key) {
      const dir = sort && sort.key === key && sort.dir === 'asc' ? 'desc' : 'asc';
      sort = { key, dir }; applySort(); paintHead(); renderBody();
      if (p.onSortChange) p.onSortChange(sort);
    }
    function applySort() {
      if (!sort) return;
      const c = cols.find((x) => x.key === sort.key);
      rows.sort((a, b) => {
        let av = c && c.sortValue ? c.sortValue(a) : a[sort.key], bv = c && c.sortValue ? c.sortValue(b) : b[sort.key];
        if (av == null) return 1; if (bv == null) return -1;
        const r = typeof av === 'number' && typeof bv === 'number' ? av - bv : String(av).localeCompare(String(bv));
        return sort.dir === 'asc' ? r : -r;
      });
    }
    function paintHead() {
      headCells.forEach((th) => {
        const key = th.dataset.key;
        th.dataset.sort = sort && sort.key === key ? sort.dir : '';
      });
    }
    function emitSelection() { if (p.onSelectionChange) p.onSelectionChange([...selected]); }
    function renderBody() {
      tbody.innerHTML = '';
      rows.forEach((row, i) => {
        const k = keyOf(row, i);
        const tr = h('tr', { class: 'dt-row', 'data-state': selected.has(k) ? 'selected' : '' });
        if (p.selectable) {
          const cb = Checkbox({ checked: selected.has(k), onCheckedChange: (on) => { on ? selected.add(k) : selected.delete(k); tr.dataset.state = on ? 'selected' : ''; emitSelection(); } });
          tr.appendChild(h('td', { class: 'dt-td dt-check' }, cb.el));
        }
        cols.forEach((c) => {
          const td = h('td', { class: 'dt-td' + (c.align === 'right' ? ' is-right' : '') });
          const v = c.render ? c.render(row) : row[c.key];
          if (v && v.nodeType) td.appendChild(v); else td.innerHTML = v == null ? '' : String(v);
          tr.appendChild(td);
        });
        if (p.onRowClick) { tr.style.cursor = 'pointer'; tr.addEventListener('click', (e) => { if (e.target.closest('.dt-check')) return; p.onRowClick(row); }); }
        tbody.appendChild(tr);
      });
    }
    applySort(); paintHead(); renderBody();
    return {
      el,
      setRows: (r) => { rows = r.slice(); applySort(); renderBody(); },
      getSelection: () => [...selected],
      clearSelection: () => { selected.clear(); renderBody(); emitSelection(); },
    };
  }

  /* =========================================================
     AppShell — viewport-locked chrome for "app" pages (Forge, Console)
     header (auto) / main (1fr, scroll-owning) / status bar (auto),
     all inside 100dvh with overflow hidden so panes scroll, not the window.
     props: { header:node, main:node, status:node, statusLeft, statusRight }
     ========================================================= */
  function AppShell(props) {
    const p = props || {};
    const header = h('header', { class: 'app-header' }, p.header || null);
    const main = h('div', { class: 'app-main' }, p.main || null);
    const status = p.status
      ? h('footer', { class: 'app-status' }, p.status)
      : h('footer', { class: 'app-status' },
          h('div', { class: 'app-status-l' }, p.statusLeft || null),
          h('div', { class: 'app-status-r' }, p.statusRight || null));
    const el = h('div', { class: 'app-shell', 'data-orbital': 'app-shell' }, header, main, status);
    return {
      el, header, main, status,
      setStatus(left, right) {
        const l = status.querySelector('.app-status-l'), r = status.querySelector('.app-status-r');
        if (l && left != null) { l.innerHTML = ''; l.append(left.nodeType ? left : document.createTextNode(String(left))); }
        if (r && right != null) { r.innerHTML = ''; r.append(right.nodeType ? right : document.createTextNode(String(right))); }
      },
    };
  }

  /* =========================================================
     DISPLAY & FEEDBACK PRIMITIVES
     ========================================================= */

  /* Badge — status pill. props: { label, tone?(neutral|accent|success|warn|error), dot? } */
  function Badge(props) {
    const p = props || {};
    const el = h('span', { class: 'badge2' + (p.tone ? ' is-' + p.tone : ''), 'data-orbital': 'badge' },
      p.dot ? h('span', { class: 'badge2-dot' }) : null, p.label || '');
    return { el, setLabel: (t) => { el.lastChild.textContent = t; } };
  }

  /* StatusDot — a glowing state dot + optional label. props: { tone?, label?, pulse? } */
  function StatusDot(props) {
    const p = props || {};
    const dot = h('span', { class: 'statusdot-dot' + (p.pulse ? ' is-pulse' : '') });
    const el = h('span', { class: 'statusdot' + (p.tone ? ' is-' + p.tone : ''), 'data-orbital': 'status-dot' },
      dot, p.label ? h('span', { class: 'statusdot-label' }, p.label) : null);
    return { el, setTone: (t) => { el.className = 'statusdot is-' + t; } };
  }

  /* Avatar — initials or image. props: { name?, src?, size?(sm|md|lg) } */
  function Avatar(props) {
    const p = props || {};
    const initials = (p.name || '?').split(/\s+/).map((w) => w[0]).slice(0, 2).join('').toUpperCase();
    const el = h('span', { class: 'avatar2' + (p.size ? ' is-' + p.size : ''), 'data-orbital': 'avatar', title: p.name || null },
      p.src ? h('img', { src: p.src, alt: p.name || '' }) : h('span', { class: 'avatar2-i' }, initials));
    return { el };
  }

  /* Progress — determinate bar. props: { value?(0..100), label?, indeterminate? } */
  function Progress(props) {
    const p = props || {};
    const bar = h('div', { class: 'progress-bar' });
    const track = h('div', { class: 'progress-track' + (p.indeterminate ? ' is-indeterminate' : '') , role: 'progressbar', 'aria-valuemin': '0', 'aria-valuemax': '100' }, bar);
    const el = h('div', { class: 'progress', 'data-orbital': 'progress' },
      p.label ? h('div', { class: 'progress-head' }, h('span', null, p.label), h('span', { class: 'progress-val' }, (p.value != null ? p.value : 0) + '%')) : null, track);
    function set(v) { v = Math.max(0, Math.min(100, v)); bar.style.width = v + '%'; track.setAttribute('aria-valuenow', String(v)); const val = el.querySelector('.progress-val'); if (val) val.textContent = Math.round(v) + '%'; }
    if (!p.indeterminate) set(p.value || 0);
    return { el, setValue: set };
  }

  /* Spinner — props: { size?(sm|md|lg), label? } */
  function Spinner(props) {
    const p = props || {};
    const el = h('span', { class: 'spinner' + (p.size ? ' is-' + p.size : ''), 'data-orbital': 'spinner', role: 'status', 'aria-label': p.label || 'Loading' });
    return { el };
  }

  /* Skeleton — loading placeholder. props: { lines?, width?, height?, variant?(text|block|circle) } */
  function Skeleton(props) {
    const p = props || {};
    const v = p.variant || 'text';
    if (v === 'text' && (p.lines || 1) > 1) {
      const rows = [];
      for (let i = 0; i < p.lines; i++) rows.push(h('span', { class: 'skeleton is-text', style: 'width:' + (i === p.lines - 1 ? 60 : 100) + '%' }));
      return { el: h('div', { class: 'skeleton-stack', 'data-orbital': 'skeleton' }, ...rows) };
    }
    const el = h('span', { class: 'skeleton is-' + v, 'data-orbital': 'skeleton', style: (p.width ? 'width:' + p.width + ';' : '') + (p.height ? 'height:' + p.height + ';' : '') });
    return { el };
  }

  /* EmptyState — props: { icon?(node), title, message?, action?{label,onClick} } */
  function EmptyState(props) {
    const p = props || {};
    const el = h('div', { class: 'empty-state', 'data-orbital': 'empty-state' },
      p.icon ? h('div', { class: 'empty-state-icon' }, p.icon) : null,
      h('div', { class: 'empty-state-title' }, p.title || 'Nothing here'),
      p.message ? h('div', { class: 'empty-state-msg' }, p.message) : null,
      p.action ? h('button', { class: 'btn', type: 'button', onclick: p.action.onClick }, p.action.label) : null);
    return { el };
  }

  /* Breadcrumbs — props: { items:[{label, href?, onClick?}] } (last = current) */
  function Breadcrumbs(props) {
    const p = props || {};
    const items = p.items || [];
    const kids = [];
    items.forEach((it, i) => {
      const last = i === items.length - 1;
      if (last) kids.push(h('span', { class: 'crumb-cur', 'aria-current': 'page' }, it.label));
      else {
        kids.push(it.href || it.onClick
          ? h('a', { class: 'crumb-link', href: it.href || '#', onclick: it.onClick ? (e) => { if (!it.href) e.preventDefault(); it.onClick(); } : null }, it.label)
          : h('span', { class: 'crumb-link' }, it.label));
        kids.push(h('span', { class: 'crumb-sep', 'aria-hidden': 'true' }, '/'));
      }
    });
    const el = h('nav', { class: 'crumbs2', 'data-orbital': 'breadcrumbs', 'aria-label': 'Breadcrumb' }, ...kids);
    return { el };
  }

  /* Pagination — props: { total, pageSize?, page?, onPageChange? } */
  function Pagination(props) {
    const p = props || {};
    const pageSize = p.pageSize || 10;
    const pages = Math.max(1, Math.ceil((p.total || 0) / pageSize));
    let cur = Math.min(Math.max(1, p.page || 1), pages);
    const el = h('nav', { class: 'pagination', 'data-orbital': 'pagination', 'aria-label': 'Pagination' });
    const prev = h('button', { type: 'button', class: 'page-btn is-edge', 'aria-label': 'Previous' }, '‹');
    const next = h('button', { type: 'button', class: 'page-btn is-edge', 'aria-label': 'Next' }, '›');
    function window_() {
      // 1 … (cur-1) cur (cur+1) … pages
      const set = new Set([1, pages, cur, cur - 1, cur + 1]);
      const arr = [...set].filter((n) => n >= 1 && n <= pages).sort((a, b) => a - b);
      const out = []; let prevN = 0;
      arr.forEach((n) => { if (n - prevN > 1) out.push('…'); out.push(n); prevN = n; });
      return out;
    }
    function render() {
      el.innerHTML = '';
      el.append(prev);
      window_().forEach((n) => {
        if (n === '…') { el.append(h('span', { class: 'page-gap' }, '…')); return; }
        const b = h('button', { type: 'button', class: 'page-btn', 'data-state': n === cur ? 'active' : 'inactive', 'aria-current': n === cur ? 'page' : null }, String(n));
        b.addEventListener('click', () => go(n));
        el.append(b);
      });
      el.append(next);
      prev.disabled = cur === 1; next.disabled = cur === pages;
    }
    function go(n) { n = Math.min(Math.max(1, n), pages); if (n === cur) return; cur = n; render(); if (p.onPageChange) p.onPageChange(cur); }
    prev.addEventListener('click', () => go(cur - 1));
    next.addEventListener('click', () => go(cur + 1));
    render();
    return { el, get page() { return cur; }, setPage: go, get pages() { return pages; } };
  }

  /* =========================================================
     SidebarShell — collapsible side tray + topbar + content + status
     The Console's full chrome, as a primitive. Sibling to AppShell.
     props:{
       brand:{name, mark?(node)},
       groups:[{label?, items:[{id,label,icon?(node),count?}]}],
       active?, onNavigate?(id),
       user?:{initials, name, role},
       crumbs?:[string], search?:{label?, hint?, onClick}, actions?:[{icon,title,onClick}],
       statusLeft?, statusRight?, content?(node)
     }
     ========================================================= */
  function SidebarShell(props) {
    const p = props || {};
    const brand = p.brand || {};
    let active = p.active;

    // sidebar nav
    const navEl = h('nav', { class: 'shell-nav' });
    const itemEls = {};
    (p.groups || []).forEach((g) => {
      if (g.label) navEl.appendChild(h('div', { class: 'shell-navgroup' }, g.label));
      (g.items || []).forEach((it) => {
        const el = h('button', { type: 'button', class: 'shell-navitem', 'data-state': it.id === active ? 'active' : 'inactive', 'data-id': it.id },
          it.icon ? h('span', { class: 'shell-navicon' }, it.icon) : null,
          h('span', { class: 'shell-navlabel' }, it.label),
          it.count != null ? h('span', { class: 'shell-navcount' }, String(it.count)) : null);
        el.addEventListener('click', () => { api.navigate(it.id); });
        itemEls[it.id] = el; navEl.appendChild(el);
      });
    });
    const sidebar = h('aside', { class: 'shell-sidebar' },
      h('div', { class: 'shell-brand' }, brand.mark || null, brand.name ? h('span', { class: 'shell-brandnm' }, brand.name) : null),
      navEl,
      p.user ? h('div', { class: 'shell-user' },
        h('span', { class: 'shell-avatar' }, p.user.initials || '?'),
        h('div', { class: 'shell-who' }, h('div', { class: 'a' }, p.user.name || ''), h('div', { class: 'b' }, p.user.role || ''))) : null);

    // topbar
    const railBtn = h('button', { class: 'shell-icon', type: 'button', 'aria-label': 'Toggle sidebar' },
      h('span', { html: '<svg width="15" height="15" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4"><path d="M2 4h12M2 8h12M2 12h12"/></svg>' }));
    const crumbEl = h('div', { class: 'shell-crumbs' });
    function paintCrumbs(arr) { crumbEl.innerHTML = ''; (arr || []).forEach((c, i) => { if (i) crumbEl.appendChild(h('span', { class: 'shell-crumbsep' }, '/')); crumbEl.appendChild(h('span', { class: i === arr.length - 1 ? 'shell-crumbcur' : '' }, c)); }); }
    paintCrumbs(p.crumbs);
    const searchBtn = p.search ? h('button', { class: 'shell-search', type: 'button', onclick: p.search.onClick },
      h('span', { html: '<svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4"><circle cx="7" cy="7" r="5"/><path d="M11 11l3 3"/></svg>' }),
      p.search.label || 'Search', p.search.hint ? h('span', { class: 'shell-kbd' }, p.search.hint) : null) : null;
    const actionEls = (p.actions || []).map((a) => h('button', { class: 'shell-icon', type: 'button', title: a.title || '', 'aria-label': a.title || '', onclick: a.onClick }, a.icon || null));
    const topbar = h('header', { class: 'shell-topbar' }, railBtn, crumbEl, searchBtn, ...actionEls);

    const content = h('div', { class: 'shell-content' }, p.content || null);
    const status = h('footer', { class: 'app-status' },
      h('div', { class: 'app-status-l' }, p.statusLeft || null),
      h('div', { class: 'app-status-r' }, p.statusRight || null));
    const mainCol = h('div', { class: 'shell-maincol' }, topbar, content, status);
    const scrim = h('div', { class: 'shell-scrim' });
    const el = h('div', { class: 'shell', 'data-orbital': 'sidebar-shell', 'data-rail': 'open' }, sidebar, mainCol, scrim);

    // collapse: desktop = rail (narrow/hidden), mobile = overlay
    railBtn.addEventListener('click', () => { el.dataset.rail = el.dataset.rail === 'open' ? 'closed' : 'open'; });
    scrim.addEventListener('click', () => { el.dataset.rail = 'closed'; });

    const api = {
      el, content, status,
      navigate(id) {
        active = id;
        Object.keys(itemEls).forEach((k) => itemEls[k].dataset.state = k === id ? 'active' : 'inactive');
        if (window.matchMedia('(max-width:860px)').matches) el.dataset.rail = 'closed';
        if (p.onNavigate) p.onNavigate(id);
      },
      setContent(node) { content.innerHTML = ''; if (node) content.append(node.nodeType ? node : document.createTextNode(String(node))); },
      setCrumbs(arr) { paintCrumbs(arr); },
      setStatus(left, right) {
        const l = status.querySelector('.app-status-l'), r = status.querySelector('.app-status-r');
        if (left != null) { l.innerHTML = ''; l.append(left.nodeType ? left : document.createTextNode(String(left))); }
        if (right != null) { r.innerHTML = ''; r.append(right.nodeType ? right : document.createTextNode(String(right))); }
      },
      toggleRail() { el.dataset.rail = el.dataset.rail === 'open' ? 'closed' : 'open'; },
    };
    return api;
  }

  /* =========================================================
     NavBar — the federated top bar (brand · entities · sections)
     props: {
       brand: { ns?, name, href?, mark? },        // ns optional muted prefix
       entities: [{label, href, here?}],           // tier-1 (Hypermodern/Straylight/Orbital)
       sections: [{label, href, here?, id?}],       // tier-2, after a divider
       onSection?: (id)=>{}                         // optional click handler for sections w/ id
     }
     The theme toggle auto-injects via orbital-theme.js. CSS lives in orbital.css.
     ========================================================= */
  function NavBar(props){
    const p = props || {};
    const b = p.brand || {};
    const mk = b.mark === false ? null
      : h('span',{class:'mk',html:'<svg viewBox="0 0 96 66" fill="currentColor"><path d="m 18,18 v 20 l -17.32,10 10,17.32 h 40 l 10,-17.32 17.32,10 17.32,-10 -10,-17.32 h -20 v -20 L 48,.68 l -10,17.32 z"/></svg>'});
    const brandInner = [mk,
      b.ns ? h('span',{class:'ns'},b.ns) : null,
      b.ns ? h('span',{class:'sep'},'//') : null,
      h('span',{class:'t'}, b.name||'')];
    const brand = b.href
      ? h('a',{class:'brand',href:b.href}, ...brandInner.filter(Boolean))
      : h('span',{class:'brand'}, ...brandInner.filter(Boolean));

    const links = [];
    (p.entities||[]).forEach(e=> links.push(h('a',{href:e.href, class:e.here?'here':null}, e.label)));
    if ((p.entities||[]).length && (p.sections||[]).length) links.push(h('span',{class:'nav-div'}));
    (p.sections||[]).forEach(s=>{
      const a = h('a',{href:s.href||'#', class:s.here?'here':null}, s.label);
      if (s.id && p.onSection) a.addEventListener('click',(ev)=>{ if(!s.href){ev.preventDefault();} p.onSection(s.id); });
      links.push(a);
    });
    const topnav = h('div',{class:'topnav'}, ...links);
    const el = h('nav',{class:'bar','data-orbital':'navbar'}, brand, topnav);
    return { el, topnav, setActive:(label)=>topnav.querySelectorAll('a').forEach(a=>a.classList.toggle('here', a.textContent.trim()===label)) };
  }

  /* =========================================================
     Footer — left / optional center / right slots
     props: { left, center?, right }   (string | node each)
     ========================================================= */
  function Footer(props){
    const p = props || {};
    const slot = (v, cls)=> h('div',{class:cls}, v==null?null:(v.nodeType?v:document.createTextNode(String(v))));
    const kids = [ slot(p.left,'foot-l') ];
    if (p.center!=null) kids.push(slot(p.center,'foot-c'));
    kids.push(slot(p.right,'foot-r'));
    const el = h('div',{class:'foot','data-orbital':'footer'}, ...kids);
    return { el };
  }

  /* =========================================================
     TabBar — bottom mobile navigation. Radix-shaped: tabs from data,
     active via data-state. Markup keys off .app-tabbar / .app-tab (orbital.css).
     props: { tabs:[{id,label,icon(svg string|node),href?}], active?, onSelect? }
     ========================================================= */
  function TabBar(props) {
    var p = props || {};
    var tabs = p.tabs || [];
    var items = tabs.map(function (t) {
      var el = h(t.href ? 'a' : 'button', {
        class: 'app-tab', 'data-part': 'tab', 'data-id': t.id,
        href: t.href || null, type: t.href ? null : 'button',
      }, h('span', { class: 'ic', html: t.icon && t.icon.nodeType ? null : (t.icon || '') }, t.icon && t.icon.nodeType ? t.icon : null),
         h('span', { class: 'lab' }, t.label));
      return el;
    });
    var el = h('nav', { class: 'app-tabbar', 'data-orbital': 'tabbar' }, items);
    function paint() {
      items.forEach(function (it) { it.dataset.state = it.dataset.id === String(p.active) ? 'active' : 'inactive'; });
    }
    items.forEach(function (it, i) {
      it.addEventListener('click', function (e) {
        if (p.onSelect) { if (!tabs[i].href) e.preventDefault(); p.active = tabs[i].id; paint(); p.onSelect(tabs[i].id); }
      });
    });
    paint();
    return { el, setActive: function (id) { p.active = id; paint(); } };
  }

  /* =========================================================
     Accordion (Radix Accordion) — single|multiple expandable
     props: { items:[{value,trigger,content}], type?'single'|'multiple',
              defaultValue?, onValueChange? }
     ========================================================= */
  function Accordion(props) {
    const p = props || {};
    const multiple = p.type === 'multiple';
    let open = new Set([].concat(p.defaultValue || (multiple ? [] : (p.items && p.items[0] ? [] : []))).filter(Boolean));
    const root = h('div', { class: 'accordion', 'data-orbital': 'accordion' });
    const rows = (p.items || []).map((it) => {
      const content = h('div', { class: 'accordion-content', role: 'region' },
        it.content && it.content.nodeType ? it.content : h('div', { class: 'accordion-inner', html: String(it.content || '') }));
      const caret = h('span', { class: 'accordion-caret', 'aria-hidden': 'true' });
      const trig = h('button', { class: 'accordion-trigger', type: 'button', 'aria-expanded': 'false' },
        h('span', null, it.trigger), caret);
      const item = h('div', { class: 'accordion-item', 'data-value': it.value }, trig, content);
      trig.addEventListener('click', () => {
        const isOpen = open.has(it.value);
        if (isOpen) open.delete(it.value);
        else { if (!multiple) open.clear(); open.add(it.value); }
        paint();
        if (p.onValueChange) p.onValueChange(multiple ? [...open] : (open.size ? [...open][0] : null));
      });
      return { it, item, trig, content };
    });
    rows.forEach((r) => root.appendChild(r.item));
    function paint() {
      rows.forEach((r) => {
        const o = open.has(r.it.value);
        r.item.dataset.state = o ? 'open' : 'closed';
        r.content.dataset.state = o ? 'open' : 'closed';
        r.content.hidden = !o;
        r.trig.setAttribute('aria-expanded', o ? 'true' : 'false');
      });
    }
    paint();
    return { el: root, open: (v) => { if (!multiple) open.clear(); open.add(v); paint(); }, close: (v) => { open.delete(v); paint(); } };
  }

  /* =========================================================
     HoverCard (Radix HoverCard) — rich preview on hover/focus
     props: { trigger(node), content(node|string), side?, align?, openDelay? }
     ========================================================= */
  function HoverCard(props) {
    const p = props || {};
    const trig = p.trigger && p.trigger.nodeType ? p.trigger : h('span', { class: 'hovercard-trigger' }, p.trigger || '');
    const body = p.content && p.content.nodeType ? p.content : h('div', { html: String(p.content || '') });
    const card = h('div', { class: 'hovercard-content', role: 'dialog', 'data-state': 'closed' }, body);
    const BH = window.ORBITALBehaviors;
    let pos, t, open = false;
    function show() { clearTimeout(t); t = setTimeout(() => {
      document.body.appendChild(card); card.dataset.state = 'open'; open = true;
      if (BH && BH.Positioning) { pos = BH.Positioning(trig, card, { side: p.side || 'top', align: p.align || 'center', gap: 8 }); pos.activate(); }
    }, p.openDelay == null ? 240 : p.openDelay); }
    function hide() { clearTimeout(t); t = setTimeout(() => {
      if (!open) return; card.dataset.state = 'closed'; pos && pos.deactivate();
      setTimeout(() => card.parentNode && card.remove(), 160); open = false;
    }, 120); }
    [trig, card].forEach((n) => { n.addEventListener('mouseenter', show); n.addEventListener('mouseleave', hide); });
    trig.addEventListener('focus', show); trig.addEventListener('blur', hide);
    return { el: trig };
  }

  /* =========================================================
     Combobox — text filter + selectable listbox (autocomplete)
     props: { options:[{value,label,hint?}], placeholder?, value?, onValueChange? }
     ========================================================= */
  function Combobox(props) {
    const p = props || {};
    const opts = p.options || [];
    let value = p.value || null, active = 0, openState = false;
    const input = h('input', { class: 'combobox-input', type: 'text', placeholder: p.placeholder || 'Search…', autocomplete: 'off', spellcheck: 'false', role: 'combobox', 'aria-expanded': 'false' });
    const list = h('div', { class: 'combobox-list', role: 'listbox' });
    const empty = h('div', { class: 'combobox-empty' }, 'No matches.');
    const panel = h('div', { class: 'combobox-panel', 'data-state': 'closed' }, list, empty);
    const el = h('div', { class: 'combobox', 'data-orbital': 'combobox' }, h('span', { class: 'combobox-i' }), input, panel);
    let results = opts.slice();
    function render() {
      list.innerHTML = ''; empty.style.display = results.length ? 'none' : 'block';
      results.forEach((o, i) => {
        const row = h('div', { class: 'combobox-opt', role: 'option', 'data-state': i === active ? 'active' : 'inactive', 'data-v': o.value },
          h('span', null, o.label), o.hint ? h('span', { class: 'combobox-hint' }, o.hint) : null);
        row.addEventListener('mousemove', () => { active = i; paint(); });
        row.addEventListener('mousedown', (e) => { e.preventDefault(); choose(i); });
        list.appendChild(row);
      });
    }
    function paint() { [...list.children].forEach((r, i) => r.dataset.state = i === active ? 'active' : 'inactive'); }
    function openList(o) { openState = o; panel.dataset.state = o ? 'open' : 'closed'; input.setAttribute('aria-expanded', o ? 'true' : 'false'); }
    function filter() { const q = input.value.trim().toLowerCase(); results = q ? opts.filter((o) => (o.label + ' ' + (o.hint || '')).toLowerCase().includes(q)) : opts.slice(); active = 0; render(); openList(true); }
    function choose(i) { const o = results[i]; if (!o) return; value = o.value; input.value = o.label; openList(false); if (p.onValueChange) p.onValueChange(o.value); }
    input.addEventListener('focus', filter);
    input.addEventListener('input', filter);
    input.addEventListener('blur', () => setTimeout(() => openList(false), 120));
    input.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowDown') { e.preventDefault(); active = Math.min(results.length - 1, active + 1); paint(); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); active = Math.max(0, active - 1); paint(); }
      else if (e.key === 'Enter') { e.preventDefault(); choose(active); }
      else if (e.key === 'Escape') openList(false);
    });
    render();
    return { el, get value() { return value; }, setValue: (v) => { const o = opts.find((x) => x.value === v); if (o) { value = v; input.value = o.label; } } };
  }

  /* =========================================================
     NumberField — stepper with min/max/step
     props: { value?, min?, max?, step?, suffix?, onValueChange? }
     ========================================================= */
  function NumberField(props) {
    const p = props || {};
    const min = p.min == null ? -Infinity : p.min, max = p.max == null ? Infinity : p.max, step = p.step || 1;
    let value = p.value == null ? 0 : p.value;
    const input = h('input', { class: 'numfield-input', type: 'text', inputmode: 'decimal' });
    const dec = h('button', { class: 'numfield-btn', type: 'button', 'aria-label': 'Decrease' }, '−');
    const inc = h('button', { class: 'numfield-btn', type: 'button', 'aria-label': 'Increase' }, '+');
    const el = h('div', { class: 'numfield', 'data-orbital': 'number-field' }, dec, input, p.suffix ? h('span', { class: 'numfield-suffix' }, p.suffix) : null, inc);
    function set(v) { v = Math.max(min, Math.min(max, v)); value = v; input.value = String(v); dec.disabled = v <= min; inc.disabled = v >= max; if (p.onValueChange) p.onValueChange(v); }
    dec.addEventListener('click', () => set(value - step));
    inc.addEventListener('click', () => set(value + step));
    input.addEventListener('change', () => { const n = parseFloat(input.value); set(isNaN(n) ? value : n); });
    set(value);
    return { el, get value() { return value; }, setValue: set };
  }

  /* =========================================================
     Rating — star input/display
     props: { value?, max?(5), readonly?, onValueChange? }
     ========================================================= */
  function Rating(props) {
    const p = props || {};
    const max = p.max || 5; let value = p.value || 0;
    const el = h('div', { class: 'rating', 'data-orbital': 'rating', role: 'slider', 'aria-valuemin': '0', 'aria-valuemax': String(max) });
    const star = '<svg viewBox="0 0 24 24"><path d="M12 2l3 7h7l-5.5 4 2 7L12 16l-6.5 4 2-7L2 9h7z"/></svg>';
    const stars = [];
    for (let i = 1; i <= max; i++) {
      const s = h('button', { class: 'rating-star', type: 'button', 'data-i': i, 'aria-label': i + ' of ' + max, html: star, disabled: p.readonly ? '' : null });
      if (!p.readonly) {
        s.addEventListener('mouseenter', () => paint(i));
        s.addEventListener('click', () => { value = i; paint(); if (p.onValueChange) p.onValueChange(i); });
      }
      stars.push(s); el.appendChild(s);
    }
    if (!p.readonly) el.addEventListener('mouseleave', () => paint());
    function paint(hover) { const n = hover || value; stars.forEach((s, i) => s.dataset.state = (i < n) ? 'on' : 'off'); el.setAttribute('aria-valuenow', String(value)); }
    paint();
    return { el, get value() { return value; }, setValue: (v) => { value = v; paint(); } };
  }

  /* =========================================================
     Meter — labeled gauge (semantic value display, Radix-ish)
     props: { value(0..100), label?, caption?, tone? }
     ========================================================= */
  function Meter(props) {
    const p = props || {};
    const v = Math.max(0, Math.min(100, p.value || 0));
    const fill = h('div', { class: 'meter-fill', style: 'width:' + v + '%' });
    const el = h('div', { class: 'meter' + (p.tone ? ' is-' + p.tone : ''), 'data-orbital': 'meter' },
      (p.label || p.caption) ? h('div', { class: 'meter-head' }, h('span', null, p.label || ''), h('span', { class: 'meter-cap' }, p.caption != null ? p.caption : v + '%')) : null,
      h('div', { class: 'meter-track', role: 'meter', 'aria-valuenow': String(v), 'aria-valuemin': '0', 'aria-valuemax': '100' }, fill));
    return { el, setValue: (n) => { fill.style.width = Math.max(0, Math.min(100, n)) + '%'; } };
  }

  /* Separator — semantic divider (Radix Separator) */
  function Separator(props) {
    const p = props || {};
    return { el: h('div', { class: 'separator' + (p.vertical ? ' is-vertical' : ''), role: 'separator', 'aria-orientation': p.vertical ? 'vertical' : 'horizontal' }, p.label ? h('span', { class: 'separator-label' }, p.label) : null) };
  }

  /* Toolbar — grouped action bar with separators (Radix Toolbar) */
  function Toolbar(props) {
    const p = props || {};
    const el = h('div', { class: 'toolbar', 'data-orbital': 'toolbar', role: 'toolbar' });
    (p.groups || []).forEach((g, gi) => {
      if (gi) el.appendChild(h('div', { class: 'toolbar-sep' }));
      g.forEach((it) => {
        if (it.el) { el.appendChild(it.el); return; }
        const b = h('button', { class: 'toolbar-btn' + (it.active ? ' on' : ''), type: 'button', title: it.label || '' }, it.icon ? h('span', { class: 'toolbar-ic', html: it.icon }) : (it.label || ''));
        if (it.onClick) b.addEventListener('click', () => it.onClick(b));
        el.appendChild(b);
      });
    });
    return { el };
  }

  /* helper: lightweight portal for UI-scope overlays */
  function uiPortal(){ var p=document.querySelector('.orbital-portal'); if(!p){p=h('div',{class:'orbital-portal'});document.body.appendChild(p);} return p; }

  /* =========================================================
     Sheet — bottom/side drawer (FocusTrap × ScrollLock × Dismissable)
     props:{ side?'bottom'|'right'|'left', title?, content, footer?, open?, onOpenChange? }
     ========================================================= */
  function Sheet(props){
    const p=props||{}; const BH=window.ORBITALBehaviors; let open=!!p.open;
    const body=p.content&&p.content.nodeType?p.content:h('div',{html:String(p.content||'')});
    const handle=h('div',{class:'sheet-handle'});
    const closeBtn=h('button',{class:'sheet-close',type:'button','aria-label':'Close'},'×');
    const panel=h('div',{class:'sheet-panel is-'+(p.side||'bottom'),role:'dialog','aria-modal':'true','data-state':'closed'},
      (p.side||'bottom')==='bottom'?handle:null, closeBtn,
      p.title?h('div',{class:'sheet-title'},p.title):null, h('div',{class:'sheet-body'},body),
      p.footer?h('div',{class:'sheet-footer'},p.footer):null);
    const overlay=h('div',{class:'sheet-overlay','data-state':'closed'},panel);
    const host=h('div',{class:'sheet','data-orbital':'sheet'},overlay);
    let beh=null;
    function build(){ return BH?BH.compose([BH.ScrollLock(),BH.FocusTrap(panel,{initialFocus:closeBtn}),BH.Dismissable(panel,{onDismiss:()=>api.setOpen(false)})]):{activate(){},deactivate(){}}; }
    closeBtn.addEventListener('click',()=>api.setOpen(false));
    const api={ el:host, panel, get open(){return open;}, setOpen(v){ v=!!v; if(v===open)return; open=v;
      if(open){ uiPortal().appendChild(host); overlay.dataset.state=panel.dataset.state='open'; beh=build(); beh.activate(); }
      else{ overlay.dataset.state=panel.dataset.state='closed'; beh&&beh.deactivate(); setTimeout(()=>host.parentNode&&host.remove(),300); }
      if(p.onOpenChange)p.onOpenChange(open); } };
    if(open){ uiPortal().appendChild(host); overlay.dataset.state=panel.dataset.state='open'; requestAnimationFrame(()=>{beh=build();beh.activate();}); }
    return api;
  }

  /* =========================================================
     ContextMenu — right-click menu at cursor (Positioning × Dismissable)
     props:{ target(node), items:[{label,onSelect,disabled?}|{separator:true}] }
     ========================================================= */
  function ContextMenu(props){
    const p=props||{}; const BH=window.ORBITALBehaviors; let dismiss=null;
    const menu=h('div',{class:'menu-content','data-orbital':'context-menu',role:'menu','data-state':'closed'});
    (p.items||[]).forEach((it)=>{ if(it.separator){menu.appendChild(h('div',{class:'menu-separator'}));return;}
      const mi=h('button',{class:'menu-item',type:'button',role:'menuitem',disabled:it.disabled?'':null},it.label);
      mi.addEventListener('click',()=>{ if(it.disabled)return; it.onSelect&&it.onSelect(); close(); }); menu.appendChild(mi); });
    function open(x,y){ uiPortal().appendChild(menu); menu.dataset.state='open';
      menu.style.position='fixed'; menu.style.left=Math.min(x,innerWidth-200)+'px'; menu.style.top=Math.min(y,innerHeight-menu.offsetHeight-8)+'px';
      dismiss=BH&&BH.Dismissable(menu,{onDismiss:close}); dismiss&&dismiss.activate(); }
    function close(){ menu.dataset.state='closed'; dismiss&&dismiss.deactivate(); setTimeout(()=>menu.parentNode&&menu.remove(),140); }
    if(p.target) p.target.addEventListener('contextmenu',(e)=>{ e.preventDefault(); open(e.clientX,e.clientY); });
    return { el:menu, open, close };
  }

  /* =========================================================
     NavigationMenu — horizontal triggers with dropdown panels
     props:{ items:[{label, panel(node|string)|href}] }
     ========================================================= */
  function NavigationMenu(props){
    const p=props||{}; let openIdx=-1; const triggers=[]; const panels=[];
    const bar=h('div',{class:'navmenu-bar'}); const drop=h('div',{class:'navmenu-drop','data-state':'closed'});
    (p.items||[]).map((it,i)=>{
      const t=h(it.href?'a':'button',it.href?{class:'navmenu-trigger',href:it.href}:{class:'navmenu-trigger',type:'button'},it.label);
      triggers.push(t); bar.appendChild(t);
      if(it.panel){ const pn=h('div',{class:'navmenu-panel'},it.panel.nodeType?it.panel:h('div',{html:String(it.panel)})); panels[i]=pn;
        t.addEventListener('click',(e)=>{e.preventDefault(); toggle(i);});
        t.addEventListener('mouseenter',()=>{ if(openIdx>=0&&openIdx!==i) show(i); }); }
    });
    const el=h('div',{class:'navmenu','data-orbital':'navigation-menu'},bar,drop);
    el.addEventListener('mouseleave',()=>hide());
    function show(i){ openIdx=i; drop.innerHTML=''; drop.appendChild(panels[i]); drop.dataset.state='open'; triggers.forEach((t,j)=>t.dataset.state=j===i?'active':''); }
    function hide(){ openIdx=-1; drop.dataset.state='closed'; triggers.forEach((t)=>t.dataset.state=''); }
    function toggle(i){ openIdx===i?hide():show(i); }
    return { el, show, hide };
  }

  /* =========================================================
     Calendar — month grid date picker
     props:{ value?(Date), onSelect?, min?, max? }
     ========================================================= */
  function Calendar(props){
    const p=props||{}; const MON=['January','February','March','April','May','June','July','August','September','October','November','December'];
    let view=new Date(p.value||Date.now()); view.setDate(1); let sel=p.value?new Date(p.value):null;
    const title=h('div',{class:'cal-title'}); const grid=h('div',{class:'cal-grid'});
    const prev=h('button',{class:'cal-nav',type:'button','aria-label':'Previous month'},'‹');
    const next=h('button',{class:'cal-nav',type:'button','aria-label':'Next month'},'›');
    const head=h('div',{class:'cal-head'},prev,title,next);
    const dow=h('div',{class:'cal-dow'},...['S','M','T','W','T','F','S'].map((d)=>h('span',null,d)));
    const el=h('div',{class:'calendar','data-orbital':'calendar'},head,dow,grid);
    function same(a,b){return a&&b&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();}
    function render(){ title.textContent=MON[view.getMonth()]+' '+view.getFullYear(); grid.innerHTML='';
      const first=new Date(view); const start=first.getDay(); const days=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();
      for(let i=0;i<start;i++) grid.appendChild(h('span',{class:'cal-cell is-empty'}));
      const today=new Date();
      for(let d=1;d<=days;d++){ const date=new Date(view.getFullYear(),view.getMonth(),d);
        const c=h('button',{class:'cal-cell',type:'button'},String(d));
        if(same(date,today))c.dataset.today='';
        if(same(date,sel))c.dataset.state='selected';
        c.addEventListener('click',()=>{ sel=date; render(); if(p.onSelect)p.onSelect(date); }); grid.appendChild(c); } }
    prev.addEventListener('click',()=>{view.setMonth(view.getMonth()-1);render();});
    next.addEventListener('click',()=>{view.setMonth(view.getMonth()+1);render();});
    render();
    return { el, get value(){return sel;}, setValue:(d)=>{sel=new Date(d);view=new Date(d);view.setDate(1);render();} };
  }

  /* =========================================================
     Stepper — horizontal step progress
     props:{ steps:[label], active?(0), onStepChange? }
     ========================================================= */
  function Stepper(props){
    const p=props||{}; const steps=p.steps||[]; let active=p.active||0;
    const el=h('div',{class:'stepper','data-orbital':'stepper'});
    const nodes=steps.map((label,i)=>{
      const dot=h('span',{class:'stepper-dot'},h('span',{class:'stepper-n'},String(i+1)));
      const node=h('button',{class:'stepper-step',type:'button'},dot,h('span',{class:'stepper-label'},label));
      node.addEventListener('click',()=>api.setStep(i));
      if(i)el.appendChild(h('span',{class:'stepper-line'})); el.appendChild(node); return node;
    });
    function paint(){ nodes.forEach((n,i)=>n.dataset.state=i<active?'done':i===active?'active':'upcoming');
      [...el.querySelectorAll('.stepper-line')].forEach((l,i)=>l.dataset.state=i<active?'done':''); }
    const api={ el, get step(){return active;}, setStep(i){ active=Math.max(0,Math.min(steps.length-1,i)); paint(); if(p.onStepChange)p.onStepChange(active); } };
    paint(); return api;
  }

  /* toast — variant convenience over the overlay Toaster (singleton) */
  let _toaster=null;
  function toast(opts){ const O=window.ORBITALOverlays; if(!O||!O.Toaster)return;
    if(!_toaster)_toaster=O.Toaster({placement:(opts&&opts.placement)||'bottom-right'});
    const o=opts||{}; return _toaster.toast({ title:o.title, message:o.message, tone:o.tone||o.variant||'info', duration:o.duration, action:o.action }); }

  root.ORBITAL = { h, SegmentedControl, Tabs, Toggle, Switch, CopyButton, Disclosure, PageIndicator, ScrollProgress, CodeSnippet, CodeViewer, TextField, Select, Checkbox, RadioGroup, Slider, DataTable, AppShell, SidebarShell, Badge, StatusDot, Avatar, Progress, Spinner, Skeleton, EmptyState, Breadcrumbs, Pagination, NavBar, Footer, TabBar, Accordion, HoverCard, Combobox, NumberField, Rating, Meter, Separator, Toolbar, Sheet, ContextMenu, NavigationMenu, Calendar, Stepper, toast };
})(window);


/* ===== orbital-overlays.js ===== */
/* ============================================================
   HM OVERLAYS — composed from orbital-behaviors.js + orbital-ui.js
   "Swiss Bank in Orbital Cyberspace"

   Each overlay is a product of behaviors, not a monolith:
     Dialog        = Disclosure × FocusTrap × ScrollLock × AriaHider × Dismissable
     Toast/Toaster = Timer × Dismissable × live-region
     DropdownMenu  = Disclosure × Positioning × RovingFocus × Dismissable
     Popover       = Disclosure × Positioning × Dismissable
     Tooltip       = Disclosure × Positioning
     CommandPalette= Dialog × Selection × Filtering

   Requires orbital-behaviors.js (window.ORBITALBehaviors) and orbital-ui.js (window.ORBITAL.h).
   Markup: semantic {component}-{part} classes + Radix data-state.
   ============================================================ */
(function (root) {
  'use strict';
  const HM = root.ORBITAL || {};
  const B = root.ORBITALBehaviors || {};
  const h = ORBITAL.h;
  function esc(s){return String(s).replace(/[&<>"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}

  /* portal root (one, shared) */
  let portal = null;
  function getPortal() {
    if (!portal) { portal = h('div', { class: 'orbital-portal' }); document.body.appendChild(portal); }
    return portal;
  }

  /* =========================================================
     Dialog
     props: { title?, description?, content:(node|string),
              footer?, open?, defaultOpen?, onOpenChange?,
              dismissable?(=true), size? }
     ========================================================= */
  function Dialog(props) {
    const p = props || {};
    let open = !!p.defaultOpen || !!p.open;

    const body = p.content && p.content.nodeType ? p.content : h('div', { html: String(p.content || '') });
    const closeBtn = h('button', { type: 'button', class: 'dialog-close', 'aria-label': 'Close' }, '\u00d7');
    const titleEl = p.title ? h('h2', { class: 'dialog-title', id: 'dlg-t-' + Math.random().toString(36).slice(2, 7) }, p.title) : null;
    const descEl = p.description ? h('p', { class: 'dialog-description' }, p.description) : null;
    const panel = h('div', {
      class: 'dialog-content' + (p.size ? ' is-' + p.size : ''), role: p.alert ? 'alertdialog' : 'dialog',
      'aria-modal': 'true', 'aria-labelledby': titleEl ? titleEl.id : null,
    }, closeBtn, titleEl, descEl, body, p.footer ? h('div', { class: 'dialog-footer' }, p.footer) : null);
    const overlay = h('div', { class: 'dialog-overlay', 'data-state': 'closed' }, panel);
    const host = h('div', { class: 'dialog', 'data-orbital': 'dialog' }, overlay);

    const behaviors = B.compose([
      B.ScrollLock(),
      B.AriaHider(overlay),
      B.FocusTrap(panel, { initialFocus: titleEl ? null : closeBtn }),
      p.dismissable === false ? null : B.Dismissable(panel, { onDismiss: () => api.setOpen(false) }),
    ]);

    closeBtn.addEventListener('click', () => api.setOpen(false));

    function render() {
      overlay.dataset.state = open ? 'open' : 'closed';
      panel.dataset.state = open ? 'open' : 'closed';
    }
    const api = {
      el: host, panel,
      get open() { return open; },
      setOpen(v) {
        v = !!v; if (v === open) return;
        open = v;
        if (open) { getPortal().appendChild(host); render(); behaviors.activate(); }
        else { render(); behaviors.deactivate(); setTimeout(() => { if (!open && host.parentNode) host.parentNode.removeChild(host); }, 220); }
        if (p.onOpenChange) p.onOpenChange(open);
      },
    };
    if (open) { getPortal().appendChild(host); render(); requestAnimationFrame(() => behaviors.activate()); }
    return api;
  }

  /* =========================================================
     Toaster + toast()  (Timer × Dismissable × live-region)
     ========================================================= */
  function Toaster(opts) {
    const o = opts || {};
    const region = h('div', { class: 'toaster', 'data-orbital': 'toaster', role: 'region', 'aria-label': 'Notifications', 'aria-live': 'polite' });
    region.dataset.placement = o.placement || 'bottom-right';
    getPortal().appendChild(region);
    function push(t) {
      t = t || {};
      const closeBtn = h('button', { type: 'button', class: 'toast-close', 'aria-label': 'Dismiss' }, '\u00d7');
      const el = h('div', { class: 'toast' + (t.tone ? ' is-' + t.tone : ''), 'data-state': 'open', role: 'status' },
        t.title ? h('div', { class: 'toast-title' }, t.title) : null,
        t.message ? h('div', { class: 'toast-message' }, t.message) : null,
        t.action ? h('button', { class: 'toast-action', type: 'button', onclick: () => { t.action.onClick && t.action.onClick(); dismiss(); } }, t.action.label) : null,
        closeBtn);
      let timer;
      function dismiss() { el.dataset.state = 'closed'; clearTimeout(timer); setTimeout(() => el.parentNode && el.remove(), 240); }
      closeBtn.addEventListener('click', dismiss);
      const dur = t.duration == null ? 4200 : t.duration;
      if (dur > 0) timer = setTimeout(dismiss, dur);
      el.addEventListener('mouseenter', () => clearTimeout(timer));
      el.addEventListener('mouseleave', () => { if (dur > 0) timer = setTimeout(dismiss, 1500); });
      region.appendChild(el);
      return { dismiss };
    }
    return { el: region, toast: push };
  }

  /* =========================================================
     DropdownMenu  (Disclosure × Positioning × RovingFocus × Dismissable)
     props: { trigger(node|string), items:[{label,onSelect,disabled?}|{separator:true}],
              side?, align? }
     ========================================================= */
  function DropdownMenu(props) {
    const p = props || {};
    let open = false;
    const trig = p.trigger && p.trigger.nodeType ? p.trigger
      : h('button', { type: 'button', class: 'btn' }, p.trigger || 'Menu');
    trig.classList.add('menu-trigger'); trig.setAttribute('aria-haspopup', 'menu'); trig.setAttribute('aria-expanded', 'false');

    const menu = h('div', { class: 'menu-content', role: 'menu', 'data-state': 'closed', tabindex: '-1' });
    const itemEls = [];
    (p.items || []).forEach((it) => {
      if (it.separator) { menu.appendChild(h('div', { class: 'menu-separator', role: 'separator' })); return; }
      const mi = h('button', { type: 'button', class: 'menu-item', role: 'menuitem', tabindex: '-1', disabled: it.disabled ? '' : null }, it.label);
      mi.addEventListener('click', () => { if (it.disabled) return; it.onSelect && it.onSelect(); api.setOpen(false); });
      itemEls.push(mi); menu.appendChild(mi);
    });

    let pos, dismiss; let idx = -1;
    function focusItem(i) { if (!itemEls.length) return; idx = (i + itemEls.length) % itemEls.length; itemEls[idx].focus(); }
    menu.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowDown') { e.preventDefault(); focusItem(idx + 1); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); focusItem(idx - 1); }
      else if (e.key === 'Home') { e.preventDefault(); focusItem(0); }
      else if (e.key === 'End') { e.preventDefault(); focusItem(itemEls.length - 1); }
    });

    const host = h('div', { class: 'menu', 'data-orbital': 'menu' }, trig);
    trig.addEventListener('click', () => api.setOpen(!open));

    const api = {
      el: host, menu,
      get open() { return open; },
      setOpen(v) {
        v = !!v; if (v === open) return; open = v;
        trig.setAttribute('aria-expanded', open ? 'true' : 'false');
        if (open) {
          getPortal().appendChild(menu); menu.dataset.state = 'open';
          pos = B.Positioning(trig, menu, { side: p.side || 'bottom', align: p.align || 'start', gap: 6 });
          dismiss = B.Dismissable(menu, { onDismiss: () => api.setOpen(false), ignore: (t) => trig.contains(t) });
          pos.activate(); dismiss.activate(); idx = -1; requestAnimationFrame(() => focusItem(0));
        } else {
          menu.dataset.state = 'closed'; pos && pos.deactivate(); dismiss && dismiss.deactivate();
          setTimeout(() => menu.parentNode && menu.remove(), 160); trig.focus();
        }
      },
    };
    return api;
  }

  /* =========================================================
     Popover  (Disclosure × Positioning × Dismissable)
     ========================================================= */
  function Popover(props) {
    const p = props || {};
    let open = false;
    const trig = p.trigger && p.trigger.nodeType ? p.trigger : h('button', { type: 'button', class: 'btn' }, p.trigger || 'Open');
    trig.setAttribute('aria-haspopup', 'dialog'); trig.setAttribute('aria-expanded', 'false');
    const body = p.content && p.content.nodeType ? p.content : h('div', { html: String(p.content || '') });
    const pop = h('div', { class: 'popover-content', role: 'dialog', 'data-state': 'closed' }, body);
    const host = h('div', { class: 'popover', 'data-orbital': 'popover' }, trig);
    let pos, dismiss;
    trig.addEventListener('click', () => api.setOpen(!open));
    const api = {
      el: host, get open() { return open; },
      setOpen(v) {
        v = !!v; if (v === open) return; open = v;
        trig.setAttribute('aria-expanded', open ? 'true' : 'false');
        if (open) {
          getPortal().appendChild(pop); pop.dataset.state = 'open';
          pos = B.Positioning(trig, pop, { side: p.side || 'bottom', align: p.align || 'center', gap: 8 });
          dismiss = B.Dismissable(pop, { onDismiss: () => api.setOpen(false), ignore: (t) => trig.contains(t) });
          pos.activate(); dismiss.activate();
        } else { pop.dataset.state = 'closed'; pos && pos.deactivate(); dismiss && dismiss.deactivate(); setTimeout(() => pop.parentNode && pop.remove(), 160); }
      },
    };
    return api;
  }

  /* =========================================================
     Tooltip  (Disclosure × Positioning) — hover/focus
     ========================================================= */
  function Tooltip(props) {
    const p = props || {};
    const anchor = p.anchor;
    const tip = h('div', { class: 'tooltip-content', role: 'tooltip', 'data-state': 'closed' }, p.label || '');
    let pos, t;
    function show() { clearTimeout(t); t = setTimeout(() => { getPortal().appendChild(tip); tip.dataset.state = 'open'; pos = B.Positioning(anchor, tip, { side: p.side || 'top', align: 'center', gap: 6 }); pos.activate(); }, p.delay == null ? 300 : p.delay); }
    function hide() { clearTimeout(t); tip.dataset.state = 'closed'; pos && pos.deactivate(); setTimeout(() => tip.parentNode && tip.remove(), 140); }
    if (anchor) {
      anchor.addEventListener('mouseenter', show); anchor.addEventListener('mouseleave', hide);
      anchor.addEventListener('focus', show); anchor.addEventListener('blur', hide);
    }
    return { show, hide };
  }

  /* =========================================================
     CommandPalette  (Dialog × Selection × Filtering) — ⌘K
     props: { commands:[{id,label,hint?,group?,onRun}], placeholder? }
     ========================================================= */
  function CommandPalette(props) {
    const p = props || {};
    const cmds = p.commands || [];
    let open = false, results = cmds.slice(), active = 0;

    const input = h('input', { class: 'cmdk-input', type: 'text', placeholder: p.placeholder || 'Type a command…', spellcheck: 'false', autocomplete: 'off' });
    const list = h('div', { class: 'cmdk-list', role: 'listbox' });
    const empty = h('div', { class: 'cmdk-empty' }, 'No commands.');
    const panel = h('div', { class: 'cmdk-content', role: 'dialog', 'aria-modal': 'true', 'data-state': 'closed' },
      h('div', { class: 'cmdk-field' }, h('span', { class: 'cmdk-search' }), input, h('kbd', { class: 'cmdk-kbd' }, 'esc')),
      list, empty);
    const overlay = h('div', { class: 'cmdk-overlay', 'data-state': 'closed' }, panel);
    const host = h('div', { class: 'cmdk', 'data-orbital': 'command-palette' }, overlay);

    const behaviors = B.compose([
      B.ScrollLock(), B.AriaHider(overlay),
      B.FocusTrap(panel, { initialFocus: input }),
      B.Dismissable(panel, { onDismiss: () => api.setOpen(false) }),
    ]);

    function render() {
      list.innerHTML = '';
      empty.style.display = results.length ? 'none' : 'block';
      let lastGroup = null;
      results.forEach((c, i) => {
        if (c.group && c.group !== lastGroup) { list.appendChild(h('div', { class: 'cmdk-group' }, c.group)); lastGroup = c.group; }
        const row = h('div', { class: 'cmdk-item', role: 'option', 'data-state': i === active ? 'active' : 'inactive', 'data-i': String(i) },
          h('span', { class: 'cmdk-label' }, c.label),
          c.hint ? h('span', { class: 'cmdk-hint' }, c.hint) : null);
        row.addEventListener('mousemove', () => { if (active !== i) { active = i; paintActive(); } });
        row.addEventListener('click', () => run(i));
        list.appendChild(row);
      });
    }
    function paintActive() {
      list.querySelectorAll('.cmdk-item').forEach((r) => {
        const on = +r.dataset.i === active; r.dataset.state = on ? 'active' : 'inactive';
        if (on) r.scrollIntoView({ block: 'nearest' });
      });
    }
    function filter(q) {
      q = q.trim().toLowerCase();
      results = !q ? cmds.slice() : cmds.filter((c) => (c.label + ' ' + (c.hint || '') + ' ' + (c.group || '')).toLowerCase().includes(q));
      active = 0; render();
    }
    function run(i) { const c = results[i]; if (!c) return; api.setOpen(false); c.onRun && c.onRun(); }
    input.addEventListener('input', () => filter(input.value));
    input.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowDown') { e.preventDefault(); active = Math.min(results.length - 1, active + 1); paintActive(); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); active = Math.max(0, active - 1); paintActive(); }
      else if (e.key === 'Enter') { e.preventDefault(); run(active); }
    });

    const api = {
      el: host,
      get open() { return open; },
      setOpen(v) {
        v = !!v; if (v === open) return; open = v;
        if (open) {
          input.value = ''; filter(''); getPortal().appendChild(host);
          overlay.dataset.state = panel.dataset.state = 'open'; behaviors.activate();
        } else {
          overlay.dataset.state = panel.dataset.state = 'closed'; behaviors.deactivate();
          setTimeout(() => host.parentNode && host.remove(), 200);
        }
        if (p.onOpenChange) p.onOpenChange(open);
      },
      toggle() { api.setOpen(!open); },
    };
    if (p.hotkey !== false) {
      window.addEventListener('keydown', (e) => {
        if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); api.toggle(); }
      });
    }
    return api;
  }

  root.ORBITALOverlays = { Dialog, Toaster, DropdownMenu, Popover, Tooltip, CommandPalette, getPortal };
})(window);


/* ===== orbital-motion.js ===== */
/* ============================================================
   HM MOTION — the house motion layer
   "Swiss Bank in Orbital Cyberspace"

   The sub-perceptual quality cues, extracted from the marketing
   site so every surface can inherit them. Declarative: tag markup
   with data-attributes and call ORBITAL.motion.init() (auto-runs on load).

   Crown jewels:
     [data-reveal]            entrance when scrolled into view
     [data-reveal-stagger]    on a parent → children reveal in sequence
     [data-split]             word/char-by-word text reveal
     [data-ambient]           inject slow orbital bloom field
     .orbital-sweep / .orbital-lift     hover utilities (CSS, in orbital.css)

   All gated on prefers-reduced-motion. The single easing is --ease.
   Halogen note: reveal/split map to a Hydrogen behavior whose
   activate() wires an IntersectionObserver; ambient is pure adornment.
   ============================================================ */
(function (root) {
  'use strict';
  const reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  /* ---- reveal-on-scroll (the gem) ----
     Elements with [data-reveal] start hidden and animate in when they
     enter the viewport. A parent [data-reveal-stagger] sequences its
     [data-reveal] descendants by a per-index delay. */
  let io = null;
  function ensureObserver(root_) {
    return new IntersectionObserver((entries, obs) => {
      entries.forEach((e) => {
        if (!e.isIntersecting) return;
        const el = e.target;
        const d = parseFloat(el.dataset.revealDelay || 0);
        el.style.transitionDelay = d + 'ms';
        el.setAttribute('data-reveal-state', 'in');
        obs.unobserve(el);
      });
    }, { root: root_ || null, threshold: 0.12, rootMargin: '0px 0px -8% 0px' });
  }

  function reveal(opts) {
    const o = opts || {};
    const scope = o.scope || document;
    const observer = ensureObserver(o.root);
    // assign stagger delays
    scope.querySelectorAll('[data-reveal-stagger]').forEach((parent) => {
      const step = parseFloat(parent.dataset.revealStagger) || 70;
      const base = parseFloat(parent.dataset.revealBase) || 0;
      [...parent.querySelectorAll('[data-reveal]')].forEach((el, i) => {
        if (el.dataset.revealDelay == null || el.dataset.revealDelay === '') el.dataset.revealDelay = base + i * step;
      });
    });
    scope.querySelectorAll('[data-reveal]').forEach((el) => {
      if (el.getAttribute('data-reveal-state')) return;
      if (reduce) { el.setAttribute('data-reveal-state', 'in'); return; }
      el.setAttribute('data-reveal-state', 'out');
      observer.observe(el);
    });
    return { observer };
  }
  // safety net: anything still 'out' after a beat (in a non-scrolling
  // container, or if IO never fires) is forced in — content never sticks hidden.
  function revealSafety(scope) {
    setTimeout(() => {
      (scope || document).querySelectorAll('[data-reveal-state="out"]').forEach((el) => {
        const r = el.getBoundingClientRect();
        if (r.top < window.innerHeight * 1.1) el.setAttribute('data-reveal-state', 'in');
      });
    }, 1200);
  }

  /* ---- text split: word / char reveal ----
     <h1 data-split="word"> → each word wrapped + revealed in sequence. */
  function split(el, opts) {
    const o = opts || {};
    const mode = o.mode || el.dataset.split || 'word';
    const step = o.step != null ? o.step : (parseFloat(el.dataset.splitStep) || 60);
    const base = o.base != null ? o.base : (parseFloat(el.dataset.splitBase) || 200);
    const text = el.textContent;
    el.textContent = '';
    el.classList.add('orbital-split');
    const units = mode === 'char' ? text.split('') : text.split(/(\s+)/);
    let idx = 0;
    units.forEach((u) => {
      if (/^\s+$/.test(u)) { el.appendChild(document.createTextNode(u)); return; }
      const span = document.createElement('span');
      span.className = 'orbital-split-u';
      span.textContent = u;
      if (!reduce) span.style.animationDelay = (base + idx * step) + 'ms';
      else span.style.animation = 'none';
      el.appendChild(span);
      idx++;
    });
    return el;
  }

  /* ---- ambient orbital blooms ----
     Injects a fixed, behind-everything field of slow drifting blurred
     radial gradients. ORBITAL.motion.ambient() or [data-ambient] on <body>. */
  function ambient(opts) {
    const o = opts || {};
    if (document.querySelector('.orbital-ambient')) return;
    const field = document.createElement('div');
    field.className = 'orbital-ambient';
    field.setAttribute('aria-hidden', 'true');
    const n = o.count || 2;
    for (let i = 0; i < n; i++) field.appendChild(document.createElement('i'));
    (o.target || document.body).insertBefore(field, (o.target || document.body).firstChild);
    return field;
  }

  function init(opts) {
    const o = opts || {};
    if (o.ambient || document.body.hasAttribute('data-ambient')) ambient(o.ambientOpts);
    document.querySelectorAll('[data-split]').forEach((el) => { if (!el.classList.contains('orbital-split')) split(el); });
    reveal({ scope: o.scope });
    revealSafety(o.scope);
  }

  root.ORBITAL = root.ORBITAL || {};
  root.ORBITAL.motion = { init, reveal, revealSafety, split, ambient, reduce };
  // auto-init after load unless told not to
  if (!window.__ORBITAL_NO_AUTO_MOTION) {
    if (document.readyState === 'complete' || document.readyState === 'interactive') setTimeout(init, 0);
    else window.addEventListener('DOMContentLoaded', () => init());
  }
})(window);

